[Added] Discord Webhook Notification (#81)
JhumanJ/OpnForm pull request #83
Opened 2023-01-28 16:11 UTC by ifly-leonard

Similar to the slack notification URL, added a discord notification URL. 

<img width="575" alt="Screenshot 2023-01-28 at 9 07 23 PM" src="https://user-images.githubusercontent.com/29737466/215276809-3a8e29aa-4959-437b-8bf3-2d37699a4b95.png">

2023-01-30 00:04 UTC, jeffrey-zang commented
yooooo this looks great

2023-01-30 01:03 UTC, ifly-leonard commented
> yooooo this looks great

tenks lel. status on revu?

Formal response: I appreciate your response. Is there any update on the PR review? I know a lot of folks (including me) who are waiting for this feature to come online.

2023-01-30 09:34 UTC, JhumanJ requested changes
It's perfect, thank you! I just added one comment to remove a commented svg.
Thanks!

2023-01-30 09:34 UTC, JhumanJ commented on resources/js/components/open/forms/components/form-components/components/FormNotificationsDiscord.vue
> +        <!-- <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 inline" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path
Can you please clear this out?

2023-01-30 09:44 UTC, ifly-leonard commented
Copy. I clicked resolve. That's about it? First time contributing to OSS.

2023-01-30 09:50 UTC, JhumanJ commented on resources/js/components/open/forms/components/form-components/components/FormNotificationsDiscord.vue
> +        <!-- <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 inline" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path
Hey @ifly-leonard I should be the one to click "resolve" 😃 It's kind of a checklist for the reviewer. More about [this here](https://www.danclarke.com/resolving-pr-comments). Please ping me when you had the chance to remove the commented out SVG, and I'll merge and deploy this! 🙌

2023-02-19 12:18 UTC, JhumanJ approved these changes

2023-02-19 12:19 UTC, merged